name: date_extensions
description: A package that adds some useful utility functions to the DateTime class.
version: 0.1.0
homepage: https://github.com/lucacasonato/date_extensions

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
